src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThreadGroupPolicy.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadFactory.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java
=> MULE-12458: Potential deadlock with IO scheduler when scheduling from IO

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/config/ThreadPoolsConfigTestCase.java
* Improve stop log messages for custom schedulers
* fix broken tests
=> MULE-12453: NPE on lifecycle stop phase after deployment error

src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThreadGroupPolicy.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java
* Replace `RejectionPolicy` with a `waitAllowed` flag
=> MULE-12472: RejectionPolicy configuration is confusing

src/main/java/org/mule/service/scheduler/internal/DefaultScheduler.java, src/main/java/org/mule/service/scheduler/internal/QuartzCronJob.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java
* Just for safety, configure quartz misfire
=> MULE-13408: Fix flaky test `org.mule.test.module.scheduler.cron.CronSchedulerTestCase.test`

src/main/java/org/mule/service/scheduler/internal/AbstractRunnableFutureDecorator.java, src/main/java/org/mule/service/scheduler/internal/DefaultScheduler.java, src/main/java/org/mule/service/scheduler/internal/RunnableFutureDecorator.java, src/main/java/org/mule/service/scheduler/internal/RunnableRepeatableFutureDecorator.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java, src/test/java/org/mule/service/scheduler/internal/ThreadNameTestCase.java
=> MULE-11754: Update the names of the threads according to the executing

src/main/java/org/mule/service/scheduler/internal/ThrottledScheduler.java, src/main/java/org/mule/service/scheduler/internal/executor/AbstractByCallerPolicy.java, src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThreadGroupPolicy.java, src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThrottlingPolicy.java, src/main/java/org/mule/service/scheduler/internal/executor/SchedulerTaskThrottledException.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/BaseDefaultSchedulerTestCase.java, src/test/java/org/mule/service/scheduler/internal/DefaultSchedulerQuartzTestCase.java, src/test/java/org/mule/service/scheduler/internal/DefaultSchedulerScheduleTestCase.java, src/test/java/org/mule/service/scheduler/internal/DefaultSchedulerShutdownTestCase.java, src/test/java/org/mule/service/scheduler/internal/RunnableRepeatableFutureDecoratorTestCase.java, src/test/java/org/mule/service/scheduler/internal/ThrottledSchedulerThrottleTestCase.java
=> MULE-13475: ThrottledScheduler does not respect waitAllowed

src/main/java/org/mule/service/scheduler/internal/config/ContainerThreadPoolsConfig.java
=> MULE-13814: Remove org.apache.logging.log4j:log4j-slf4j-impl from

src/main/java/org/mule/service/scheduler/internal/AbstractRunnableFutureDecorator.java, src/main/java/org/mule/service/scheduler/internal/DefaultScheduler.java, src/test/java/org/mule/service/scheduler/internal/DefaultSchedulerScheduleTestCase.java
=> MULE-13874: DefaultScheduler#shutdownNow returns tasks that have already

src/main/java/org/mule/service/scheduler/internal/AbstractRunnableFutureDecorator.java
concurrency for GET operation
* microoptimizations
=> MULE-13779: CLONE - HTTP requester component degradation of 98% on high

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java
Removing calls to prestartAllCoreThreads() altogether since it brings
more problems than solutions.
It was intended initially to have all threads created at startup rather
than lazily creating threads, but using it causes race conditions with
the queue which causes tasks on certain situations to be skipped.
=> MULE-13942: Race condition on Executors startup with SynchronousQueue

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java, src/test/java/org/mule/service/scheduler/internal/util/Delegator.java
=> MULE-14179: HTTP connector does not dispose listeners, causing a memory

src/main/java/org/mule/service/scheduler/internal/DefaultSchedulerService.java
=> MULE-14173: Add a splash information about the thread configurations

src/main/java/org/mule/service/scheduler/internal/executor/AbstractByCallerPolicy.java, src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThreadGroupPolicy.java, src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThrottlingPolicy.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/main/resources/META-INF/mule-artifact/mule-artifact.json, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java
=> MULE-14510: Allows custom schedulers to use a `runInCaller` rejection

src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThreadGroupPolicy.java
=> MULE-14524: Schedulers don't indicate which one is exhausted

src/main/java/org/mule/service/scheduler/internal/config/ContainerThreadPoolsConfig.java
=> MULE-14552: Allow to override the location of the scheduler config file

src/main/java/org/mule/service/scheduler/internal/config/ContainerThreadPoolsConfig.java, src/test/java/org/mule/service/scheduler/internal/config/ThreadPoolsConfigTestCase.java
=> MULE-14558: Unclear error with missing parameter in scheduler

src/main/java/org/mule/service/scheduler/internal/DefaultScheduler.java, src/test/java/org/mule/service/scheduler/internal/DefaultSchedulerScheduleTestCase.java
=> MULE-14577: Delayed task is triggered when target scheduler is busy is

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java
=> MULE-14658: Too many ThreadGroup instances leaked after redeploys

src/main/java/org/mule/service/scheduler/internal/DefaultScheduler.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java
=> MULE-14675: Cannot destroy thread groups that have commons-pool evictor

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java
=> MULE-14736: Custom scheduler shutdown from a thread from the same

src/main/java/org/mule/service/scheduler/internal/DefaultSchedulerService.java, src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThreadGroupPolicy.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java
=> MULE-15415: Scheduler Service: provide a method to determine if current

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java
=> MULE-15531: Add an option to always log the creation location of a

src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThreadGroupPolicy.java
=> MULE-15588: Rejected from scheduler warning has too high frequency in

src/main/java/org/mule/service/scheduler/internal/AbstractRunnableFutureDecorator.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java
=> MULE-15666: Add data about dangling threads when a ThreadGroup can't be

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java
=> MULE-16516: Race condition in ThreadGroup destroying for customScheduler

src/main/java/org/mule/service/scheduler/internal/DefaultScheduler.java, src/main/java/org/mule/service/scheduler/internal/RepeatableTaskWrapper.java, src/main/java/org/mule/service/scheduler/internal/RunnableRepeatableFutureDecorator.java, src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThreadGroupPolicy.java, src/main/java/org/mule/service/scheduler/internal/logging/SuppressingLogger.java, src/test/java/org/mule/service/scheduler/internal/RunnableRepeatableFutureDecoratorTestCase.java
=> MULE-16759: WARN logged when fixed rate task overlap in a single thread

src/main/java/org/mule/service/scheduler/internal/DefaultScheduler.java
=> MULE-17011: Improve log messages when stopping a scheduler with pending

src/main/java/org/mule/service/scheduler/internal/threads/DedicatedSchedulerThreadPools.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/main/java/org/mule/service/scheduler/internal/threads/UberSchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/RunnableFutureDecoratorTestCase.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java
=> MULE-17673: Re deploying applications is leaking classloaders making the

src/main/java/org/mule/service/scheduler/internal/executor/ByCallerThrottlingPolicy.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java, src/test/java/org/mule/service/scheduler/internal/ThrottledSchedulerThrottleTestCase.java
=> MULE-17938: Potential deadlock when dispatching concurrent tasks to a

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java
=> MULE-18224: CustomScheduler#destroyThreadGroup taking more than

src/main/java/org/mule/service/scheduler/internal/DefaultScheduler.java
* Addendum, address another case
=> MULE-18471: Race condition between scheduler stop and scheduleWithFixedDelay leads to memory leak

src/main/java/org/mule/service/scheduler/internal/ThrottledScheduler.java, src/test/java/org/mule/service/scheduler/internal/ThrottledSchedulerThrottleTestCase.java
=> MULE-18909: ThrottledScheduler not decreasing counter after scheduled

src/main/java/org/mule/service/scheduler/internal/AbstractRunnableFutureDecorator.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java
(cherry picked from commit cfe1c7229e8b5dcf3da37c694d62ee4c5112cc15)
=> MULE-20072: Thread-locals isolation on scheduled tasks.

src/main/java/org/mule/service/scheduler/internal/DefaultSchedulerService.java, src/main/java/org/mule/service/scheduler/internal/threads/DedicatedSchedulerThreadPools.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/main/java/org/mule/service/scheduler/internal/threads/UberSchedulerThreadPools.java
(cherry picked from commit 74ae6b5a69c8f6e773c06715380d672fab4aa26f)
=> MULE-19537: App get stuck when is trying to read the error payload in the error handler after a failing http request (#168)

src/main/java/org/mule/service/scheduler/internal/config/ContainerThreadPoolsConfig.java
Reverts mulesoft/mule-scheduler-service#176
=> Revert "W-10863328: Code stabilization from Sonar input"

src/test/java/org/mule/service/scheduler/internal/DefaultSchedulerFixedDelayRepeatsTestCase.java, src/test/java/org/mule/service/scheduler/internal/DefaultSchedulerScheduleTestCase.java
=> W-13005429: Split DefaultSchedulerScheduleTestCase#fixedDelayRepeats to

src/main/java/module-info.java
=> W-13761983: Add module-info to mule services

src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadFactory.java, src/main/java/org/mule/service/scheduler/internal/threads/SchedulerThreadPools.java, src/test/java/org/mule/service/scheduler/internal/SchedulerThreadPoolsTestCase.java, src/test/java/org/mule/service/scheduler/internal/threads/SchedulerThreadFactoryTestCase.java
(cherry picked from commit 3e88f07f0683afaf55cb45814c10a1e743c56c21)
=> W-14658876: Allowing configuration of thread priority for Schedulers. (#230)

pom.xml
* Remove java 11+ specific folder
=> W-16045353: Compile with target Java 17

src/main/java/module-info.java
* do not require what is already transitive from mule-api
=> W-17068193: Replace uses of javax.inject with jakarta.inject in Mule runtime code
